# Generated by Django 5.0.6 on 2024-06-20 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="blog",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
