# Generated by Django 5.0.6 on 2024-06-21 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_blog_pub_date_blog_createdat_blog_updatedat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "blog")},
        ),
    ]
